plugins {
    id 'java-library'
    id 'maven-publish'
}

group = providers.gradleProperty('group').get()
version = providers.gradleProperty('version').get()

base {
    archivesName = 'aj-nativescript'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    withSourcesJar()
    withJavadocJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
}

tasks.named('test') {
    useJUnitPlatform()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = 'aj-nativescript'
        }
    }
}
